version: "3"
volumes:
  data:
services:

  laravel:
    build: .
    container_name: "granafa-laravel"
    volumes:
      - ./:/app
    ports:
      - 4000:80
      - 444:443
    networks:
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: 'grafana-prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # grants admin role to anonymous access
      - GF_AUTH_ANONYMOUS_ENABLED=true # removes login 1/2
      - GF_AUTH_BASIC_ENABLED=false # removes login 2/2
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

networks:
    grafana:
        external: true
    